Update 3proxy

diff --git a/3proxy b/3proxy
--- a/3proxy
+++ b/3proxy
@@ -12,21 +12,6 @@ setup_ipv6() {
 
 setup_ipv6
 
-WORKDIR="/home/proxy"
-MAXCOUNT=3333
-START_PORT=30000
-
-# Function to auto-detect network interface name
-auto_detect_interface() {
-    INTERFACE=$(ip -o link show | awk -F': ' '$2 !~ /lo|vir|^[^0-9]/ {print $2; exit}')
-}
-
-# Get IPv6 address
-get_ipv6_address() {
-    ipv6_address=$(ip addr show $INTERFACE | awk '/inet6/{print $2}' | grep -v '^fe80' | head -n1)
-    echo "$ipv6_address"
-}
-
 random() {
     tr </dev/urandom -dc A-Za-z0-9 | head -c5
     echo
@@ -54,7 +39,7 @@ install_3proxy() {
 gen_3proxy() {
     cat <<EOF
 daemon
-maxconn 4000
+maxconn 5000
 nserver 1.1.1.1
 nserver 8.8.4.4
 nserver 2001:4860:4860::8888
@@ -65,26 +50,21 @@ setgid 65535
 setuid 65535
 stacksize 6291456 
 flush
-auth strong
 
-users $(awk -F "/" 'BEGIN{ORS="";} {print $1 ":CL:" $2 " "}' ${WORKDATA})
-
-$(awk -F "/" '{print "auth strong\n" \
-"allow " $1 "\n" \
-"proxy -6 -n -a -p" $4 " -i" $3 " -e" $5 "\n" \
+$(awk -F "/" '{print "\n" \
+"" $1 "\n" \
+"proxy -6 -n -a -p" $4 " -i" $3 " -e"$5"\n" \
 "flush\n"}' ${WORKDATA})
 EOF
 }
 
 gen_proxy_file_for_user() {
-    cat >proxy.txt <<EOF
-$(awk -F "/" '{print $3 ":" $4 ":" $1 ":" $2 }' ${WORKDATA})
-EOF
+    awk -F "/" '{print $3 ":" $4}' ${WORKDATA} > proxy.txt
 }
 
 gen_data() {
-    seq $START_PORT $((START_PORT + MAXCOUNT - 1)) | while read port; do
-        echo "proxy$port/$(random)/$IP4/$port/$(gen64 $IP6)"
+    seq $FIRST_PORT $LAST_PORT | while read port; do
+        echo "//$IP4/$port/$(gen64 $IP6)"
     done
 }
 
@@ -96,53 +76,54 @@ EOF
 
 gen_ifconfig() {
     cat <<EOF
-$(awk -F "/" '{print "ifconfig $INTERFACE inet6 add " $5 "/64"}' ${WORKDATA})
+$(awk -F "/" '{print "ifconfig eth0 inet6 add " $5 "/64"}' ${WORKDATA})
 EOF
 }
 
+setup_environment() {
+    echo "Installing necessary packages"
+    yum -y install gcc net-tools bsdtar zip make >/dev/null
+}
+
+rotate_count=0
+
 rotate_ipv6() {
-    echo "Rotating IPv6 - Đang Xoay IPv6"
+    echo "Rotating IPv6 addresses..."
     IP6=$(curl -6 -s icanhazip.com | cut -f1-4 -d':')
     gen_data >$WORKDIR/data.txt
     gen_ifconfig >$WORKDIR/boot_ifconfig.sh
     bash $WORKDIR/boot_ifconfig.sh
-    echo "Xoay IPv6 Rotated successfully."
+    echo "IPv6 addresses rotated successfully."
+    rotate_count=$((rotate_count + 1))
+    echo "Rotation count: $rotate_count"
+    sleep 3600
 }
 
 download_proxy() {
-    cd $WORKDIR || return
-    curl -F "file=@proxy.txt" https://file.io
+    cd $WORKDIR || exit 1
+    curl -F "proxy.txt" https://transfer.sh
 }
 
-setup_cron_job() {
-    crontab -l > mycron
-    echo "*/10 * * * * /bin/bash -c '$WORKDIR/rotate_ipv6.sh'" >> mycron
-    crontab mycron
-    rm mycron
-}
-
-# Main setup
-echo "Cài đặt ứng dụng"
-yum -y install gcc net-tools bsdtar zip >/dev/null
-
-install_3proxy
-
-echo "Dang Thiet Lap Thu Muc +. Setup Proxy…"
-WORKDIR="/home/proxy"
+echo "working folder = /home/vlt"
+WORKDIR="/home/vlt"
 WORKDATA="${WORKDIR}/data.txt"
-mkdir -p $WORKDIR && cd $WORKDIR
+mkdir $WORKDIR && cd $_
 
-auto_detect_interface
 IP4=$(curl -4 -s icanhazip.com)
-IP6=$(ip addr show $INTERFACE | grep 'inet6 ' | awk '{print $2}' | cut -f1-4 -d':' | grep '^2')
+IP6=$(ip addr show eth0 | grep 'inet6 ' | awk '{print $2}' | cut -f1-4 -d':' | grep '^2')
 
-echo "Internal ip = ${IP4}. External sub for ip6 = ${IP6}"
+echo "Internal ip = ${IP4}. Exteranl sub for ip6 = ${IP6}"
+
+FIRST_PORT=10000
+LAST_PORT=12222
+
+setup_environment
+install_3proxy
 
 gen_data >$WORKDIR/data.txt
 gen_iptables >$WORKDIR/boot_iptables.sh
 gen_ifconfig >$WORKDIR/boot_ifconfig.sh
 chmod +x $WORKDIR/boot_*.sh /etc/rc.local
-
 gen_3proxy >/usr/local/etc/3proxy/3proxy.cfg
 
 cat >>/etc/rc.local <<EOF
@@ -156,49 +137,38 @@ chmod +x /etc/rc.local
 bash /etc/rc.local
 
 gen_proxy_file_for_user
-rm -rf /root/setup.sh
+
 rm -rf /root/3proxy-3proxy-0.8.6
 
-# Create rotate_ipv6 script
-cat >$WORKDIR/rotate_ipv6.sh <<EOF
-#!/bin/sh
-$(declare -f rotate_ipv6)
-rotate_ipv6
-EOF
-chmod +x $WORKDIR/rotate_ipv6.sh
-
-# Setup cron job for rotating IPv6 every 10 minutes
-setup_cron_job
-
 echo "Starting Proxy"
+echo "So Luong IPv6 Hien Tai:"
+ip -6 addr | grep inet6 | wc -l
 
 # Menu loop
 while true; do
-    echo "1. Xoay IPv6"
-    echo "2. Xoay IPv6 Tự Động "
-    echo "3. Download Proxy "
+    echo "1. Thiết Lập Lại 3proxy"
+    echo "2. Xoay IPV6"
+    echo "3. Download proxy"
     echo "4. Exit"
-    echo -n "Nhập lựa chọn của bạn: "
+    echo -n "Enter your choice: "
     read choice
     case $choice in
         1)
-            rotate_ipv6
-            echo "Đang Xoay IPv6"
+            install_3proxy
             ;;
         2)
-            setup_cron_job
-            echo "Tự động xoay IPv6 10 phút/1 Tự động"
+            rotate_ipv6
             ;;
         3)
             download_proxy
-            echo "Link Dow Proxy"
             ;;
         4)
             echo "Exiting..."
             exit 0
             ;;
         *)
-            echo "Lựa chọn không hợp lệ. Vui lòng thử lại."
+            echo "Invalid choice. Please try again."
             ;;
     esac
 done
+
