Update 3proxy
Signed-off-by: ️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️ <30877561+volamtuan@users.noreply.github.com>

diff --git a/3proxy b/3proxy
--- a/3proxy
+++ b/3proxy
@@ -1,16 +1,5 @@
-#!/bin/sh
+##!/bin/sh
 PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
-
-setup_ipv6() {
-    echo "Thiết lập IPv6..."
-    sudo service 3proxy stop
-    ip -6 addr flush dev eth0
-    sudo systemctl stop firewalld
-    sudo systemctl disable firewalld
-    bash <(curl -s "https://raw.githubusercontent.com/quanglinh0208/3proxy/main/ipv6.sh") 
-}
-
-setup_ipv6
 
 random() {
     tr </dev/urandom -dc A-Za-z0-9 | head -c5
@@ -29,11 +18,23 @@ install_3proxy() {
     echo "Installing 3proxy..."
     URL="https://github.com/z3APA3A/3proxy/archive/3proxy-0.8.6.tar.gz"
     wget -qO- $URL | bsdtar -xvf-
-    cd 3proxy-3proxy-0.8.6
-    make -f Makefile.Linux
+    cd 3proxy-3proxy-0.8.6 || exit
+    make -f Makefile.Linux || exit
     mkdir -p /usr/local/etc/3proxy/{bin,logs,stat}
     cp src/3proxy /usr/local/etc/3proxy/bin/
-    cd $WORKDIR
+    cd "$WORKDIR" || exit
+    echo "* hard nofile 999999" >> /etc/security/limits.conf
+    echo "* soft nofile 999999" >> /etc/security/limits.conf
+    echo "fs.file-max = 1000000" >> /etc/sysctl.conf
+    echo "net.ipv4.ip_local_port_range = 1024 65000" >> /etc/sysctl.conf
+    echo "net.ipv4.tcp_fin_timeout = 30" >> /etc/sysctl.conf
+    echo "net.core.somaxconn = 4096" >> /etc/sysctl.conf
+    echo "net.core.netdev_max_backlog = 4096" >> /etc/sysctl.conf
+    echo "net.ipv6.conf.eth0.proxy_ndp=1" >> /etc/sysctl.conf
+    echo "net.ipv6.conf.all.proxy_ndp=1" >> /etc/sysctl.conf
+    echo "net.ipv6.conf.default.forwarding=1" >> /etc/sysctl.conf
+    echo "net.ipv6.conf.all.forwarding=1" >> /etc/sysctl.conf
+    echo "net.ipv6.ip_nonlocal_bind = 1" >> /etc/sysctl.conf
 }
 
 gen_3proxy() {
@@ -50,27 +51,34 @@ setgid 65535
 setuid 65535
 stacksize 6291456 
 flush
+auth none
+authcache 86400
+allow 14.224.163.75
+allow 192.168.1.29
+allow 127.0.0.1
 
 $(awk -F "/" '{print "\n" \
-"" $1 "\n" \
+"allow *" $1 "\n" \
 "proxy -6 -n -a -p" $4 " -i" $3 " -e"$5"\n" \
 "flush\n"}' ${WORKDATA})
 EOF
 }
 
 gen_proxy_file_for_user() {
-    awk -F "/" '{print $3 ":" $4}' ${WORKDATA} > proxy.txt
+    cat > proxy.txt <<EOF
+$(awk -F "/" '{print $3 ":" $4}' ${WORKDATA})
+EOF
 }
 
 gen_data() {
-    seq $FIRST_PORT $LAST_PORT | while read port; do
+    seq $FIRST_PORT $LAST_PORT | while read -r port; do
         echo "//$IP4/$port/$(gen64 $IP6)"
     done
 }
 
 gen_iptables() {
     cat <<EOF
-$(awk -F "/" '{print "iptables -I INPUT -p tcp --dport " $4 "  -m state --state NEW -j ACCEPT"}' ${WORKDATA})
+$(awk -F "/" '{print "iptables -I INPUT -p tcp --dport " $4 " -m state --state NEW -j ACCEPT"}' ${WORKDATA})
 EOF
 }
 
@@ -80,52 +88,115 @@ $(awk -F "/" '{print "ifconfig eth0 inet6 add " $5 "/64"}' ${WORKDATA})
 EOF
 }
 
-setup_environment() {
-    echo "Installing necessary packages"
-    yum -y install gcc net-tools bsdtar zip make >/dev/null
+rotate_ipv6() {
+    IP6="2001:ee0:4f0c:8b40"
+    
+    # Sinh dữ liệu mới
+    gen_data > "$WORKDIR/$WORKDATA"
+    
+    # Tạo và áp dụng cấu hình mạng IPv6
+    gen_ifconfig > "$WORKDIR/boot_ifconfig.sh"
+    chmod +x "$WORKDIR/boot_ifconfig.sh"
+    bash "$WORKDIR/boot_ifconfig.sh"
+    
+    # Cập nhật cấu hình của 3proxy
+    gen_3proxy > /usr/local/etc/3proxy/3proxy.cfg
+    
+    # Khởi động lại dịch vụ 3proxy
+    echo "Restarting 3proxy service..."
+    systemctl restart 3proxy
+    restart_result=$?
+    
+    if [ $restart_result -eq 0 ]; then
+        echo "IPv6 addresses rotated successfully."
+        echo "[OK]: Thành công"
+    else
+        echo "Failed to rotate IPv6 addresses!"
+        echo "[ERROR]: Thất bại!"
+        exit 1
+    fi
 }
 
-download_proxy() {
-    cd $WORKDIR || exit 1
-    curl -F "proxy.txt" https://transfer.sh
-}
+# Cài đặt các ứng dụng cần thiết
+echo "Installing apps..."
+yum -y install wget gcc net-tools bsdtar zip || exit
 
-echo "working folder = /home/vlt"
-WORKDIR="/home/vlt"
-WORKDATA="${WORKDIR}/data.txt"
-mkdir $WORKDIR && cd $_
-
-IP4=$(curl -4 -s icanhazip.com)
-IP6=$(ip addr show eth0 | grep 'inet6 ' | awk '{print $2}' | cut -f1-4 -d':' | grep '^2')
-
-echo "Internal ip = ${IP4}. Exteranl sub for ip6 = ${IP6}"
-
-FIRST_PORT=10000
-LAST_PORT=12222
-
-setup_environment
 install_3proxy
 
-gen_data >$WORKDIR/data.txt
-gen_iptables >$WORKDIR/boot_iptables.sh
-gen_ifconfig >$WORKDIR/boot_ifconfig.sh
-chmod +x $WORKDIR/boot_*.sh /etc/rc.local
-gen_3proxy >/usr/local/etc/3proxy/3proxy.cfg
+# Cài đặt thư mục làm việc và biến môi trường
+echo "Setting up working folder..."
+WORKDIR="/home/vlt"
+WORKDATA="${WORKDIR}/data.txt"
+mkdir -p "$WORKDIR" && cd "$WORKDIR" || exit
 
-cat >>/etc/rc.local <<EOF
-bash ${WORKDIR}/boot_iptables.sh
-bash ${WORKDIR}/boot_ifconfig.sh
-ulimit -n 10048
-/usr/local/etc/3proxy/bin/3proxy /usr/local/etc/3proxy/3proxy.cfg
+IP4=$(ip -4 addr show eth0 | grep -oP '(?<=inet\s)\d+(\.\d+){3}' | grep -E '^192\.168\.' | head -n 1)
+IP6=$(ip -6 addr show | grep inet6 | grep -v 'scope link' | sed -n '2p' | awk '{print $2}' | cut -d':' -f1-4)
+
+echo "Internal IP = ${IP4}. External subnet for IPv6 = ${IP6}"
+
+# Nhập cổng và kiểm tra tính hợp lệ
+while :; do
+  read -p "Nhập Cổng Muốn Tạo Từ 10000 đến 63000: " FIRST_PORT
+  [[ $FIRST_PORT =~ ^[0-9]+$ ]] || { echo "Nhập số hợp lệ"; continue; }
+  if ((FIRST_PORT >= 10000 && FIRST_PORT <= 63000)); then
+    echo "OK! Valid number"
+    break
+  else
+    echo "Số nằm ngoài phạm vi, hãy thử lại (Cổng từ 10000 đến 63000)"
+  fi
+done
+
+LAST_PORT=$((FIRST_PORT + 13750))
+echo "Đang Tạo $LAST_PORT..."
+
+gen_data > "$WORKDIR/data.txt"
+gen_iptables > "$WORKDIR/boot_iptables.sh"
+gen_ifconfig > "$WORKDIR/boot_ifconfig.sh"
+chmod +x "$WORKDIR/boot_*.sh" /etc/rc.local
+
+# Tạo tệp dịch vụ systemd cho 3proxy
+cat <<EOF > /etc/systemd/system/3proxy.service
+[Unit]
+Description=3proxy Proxy Server
+After=network.target
+
+[Service]
+Type=simple
+ExecStart=/usr/local/etc/3proxy/bin/3proxy /usr/local/etc/3proxy/3proxy.cfg
+ExecReload=/bin/kill -HUP \$MAINPID
+ExecStop=/bin/kill -TERM \$MAINPID
+Restart=always
+RestartSec=5
+LimitNOFILE=1000000
+
+[Install]
+WantedBy=multi-user.target
 EOF
 
+chmod +x /etc/rc.d/rc.local
+cat >> /etc/rc.local <<EOF
+
+systemctl start NetworkManager.service
+killall 3proxy
+service 3proxy start
+bash ${WORKDIR}/boot_iptables.sh
+bash ${WORKDIR}/boot_ifconfig.sh
+ulimit -u unlimited -n 999999 -s 16384
+/usr/local/etc/3proxy/bin/3proxy /usr/local/etc/3proxy/3proxy.cfg
+EOF
 chmod +x /etc/rc.local
 bash /etc/rc.local
-
 gen_proxy_file_for_user
-
 rm -rf /root/3proxy-3proxy-0.8.6
+echo "Starting Proxy..."
 
-echo "Starting Proxy"
-echo "So Luong IPv6 Hien Tai:"
+systemctl daemon-reload
+systemctl enable 3proxy
+systemctl start 3proxy
+systemctl enable 3proxy.service
+systemctl start 3proxy.service
+systemctl stop firewalld
+systemctl disable firewalld
+
+echo “Tổng số IPv6 hiện tại:”
 ip -6 addr | grep inet6 | wc -l
